//! Slice 18a: `new --harness codex` creates a Codex sandbox with a
//! `harness-codex` mixin, and state keeps one entry per harness (decision 68).

mod common;

use assert_cmd::Command;
use common::Env;
use sbxm::backend::{CreateSpec, FakeBackend, SkillsStore};
use sbxm::commands::new;
use sbxm::harness::Harness;

fn codex() -> new::Options {
    new::Options {
        harness: Harness::Codex,
        ..Default::default()
    }
}

fn codex_kit_dir(env: &Env) -> std::path::PathBuf {
    env.kit_dir("demo").with_file_name("harness-codex")
}

#[test]
fn creates_a_codex_sandbox_with_a_harness_codex_mixin() {
    let env = Env::new();
    let backend = FakeBackend::default();

    env.run_with("demo", &codex(), &backend).unwrap();

    assert_eq!(
        backend.creates(),
        vec![CreateSpec {
            name: "sbxm-demo-codex".into(),
            agent: "codex".into(),
            workspace: env.base_dir().join("demo"),
            cpus: 4,
            memory: "8g".into(),
            skills: SkillsStore::ReadOnly,
            kits: vec![env.kit_dir("demo"), codex_kit_dir(&env)],
        }]
    );
    insta::assert_snapshot!(
        std::fs::read_to_string(codex_kit_dir(&env).join("spec.yaml")).unwrap(),
        @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-harness-codex
    description: Generated by sbxm from profile 'default' for codex. Do not edit.
    requires:
      agent: codex
    "
    );
}

#[test]
fn mandatory_instructions_become_the_codex_home_file() {
    let env = Env::new();
    env.write_profile("default", "[instructions]\nmandatory = \"mandatory.md\"\n");
    std::fs::write(
        env.profiles_dir().join("default").join("mandatory.md"),
        "Always run the tests.\n",
    )
    .unwrap();

    env.run_with("demo", &codex(), &FakeBackend::default())
        .unwrap();

    let home_file = codex_kit_dir(&env)
        .join("files")
        .join("home")
        .join(".codex")
        .join("AGENTS.md");
    assert_eq!(
        std::fs::read_to_string(home_file).unwrap(),
        "Always run the tests.\n"
    );
}

#[test]
fn state_keeps_the_claude_entry_when_codex_is_added() {
    let env = Env::new();
    let backend = FakeBackend::default();

    env.run("demo", &backend).unwrap();
    env.run_with("demo", &codex(), &backend).unwrap();

    let path = env.base_dir().join(".sbxm").join("demo").join("state.json");
    let state: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    assert_eq!(state["sandboxes"]["claude"]["sandbox"], "sbxm-demo-claude");
    assert_eq!(state["sandboxes"]["codex"]["sandbox"], "sbxm-demo-codex");
}

#[test]
fn unsupported_harness_is_rejected_and_creates_nothing() {
    let env = Env::new();

    let output = Command::cargo_bin("sbxm")
        .unwrap()
        .env("SBXM_CONFIG_DIR", env.config_dir())
        .args(["new", "demo", "--harness", "gemini"])
        .output()
        .unwrap();

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(
        stderr.contains("invalid value 'gemini' for '--harness"),
        "{stderr}"
    );
    assert!(
        stderr.contains("[possible values: claude, codex]"),
        "{stderr}"
    );
    assert!(!env.base_dir().join("demo").exists());
    assert!(!env.base_dir().join(".sbxm").exists());
}
