//! M2a slice 3: `new --harness antigravity` creates a sandbox from the pinned
//! Docker Hub kit with a `harness-antigravity` mixin (decisions 103, 104).

mod common;

use common::Env;
use sbxm::backend::{CreateSpec, FakeBackend, SkillsStore};
use sbxm::commands::new;
use sbxm::harness::Harness;

const KIT: &str = "docker.io/sbx/antigravity-kit:20260928-7da9425e640d172e36abe6de3499a1c75d416c0f";

fn antigravity() -> new::Options {
    new::Options {
        harness: Harness::Antigravity,
        ..Default::default()
    }
}

fn kit_dir(env: &Env) -> std::path::PathBuf {
    env.kit_dir("demo").with_file_name("harness-antigravity")
}

/// Runs `new demo --harness antigravity` and returns its warnings.
fn warnings(env: &Env) -> String {
    let mut warn = Vec::new();
    new::run(
        &env.config_dir(),
        "demo",
        &antigravity(),
        &FakeBackend::default(),
        &mut warn,
    )
    .unwrap();
    String::from_utf8(warn).unwrap()
}

#[test]
fn creates_a_sandbox_from_the_pinned_kit() {
    let env = Env::new();
    let backend = FakeBackend::default();

    env.run_with("demo", &antigravity(), &backend).unwrap();

    assert_eq!(
        backend.creates(),
        vec![CreateSpec {
            name: "sbxm-demo-antigravity".into(),
            agent: KIT.into(),
            workspace: env.base_dir().join("demo"),
            cpus: 4,
            memory: "8g".into(),
            skills: SkillsStore::ReadOnly,
            kits: vec![env.kit_dir("demo"), kit_dir(&env)],
        }]
    );
    insta::assert_snapshot!(
        std::fs::read_to_string(kit_dir(&env).join("spec.yaml")).unwrap(),
        @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-harness-antigravity
    description: Generated by sbxm from profile 'default' for antigravity. Do not edit.
    requires:
      agent: antigravity
    "
    );
}

#[test]
fn the_pinned_kit_is_an_immutable_dated_tag() {
    // Never `latest` (decision 104): a moving tag would change a run under the user.
    let arg = Harness::Antigravity.agent_arg();
    assert_eq!(arg, KIT);
    assert!(!arg.ends_with(":latest"));
}

#[test]
fn mandatory_instructions_become_the_gemini_agents_home_file() {
    // Verified on real sbx (P5): `~/.gemini/AGENTS.md` is loaded by `agy -p`;
    // the same file under `~/.gemini/antigravity-cli/` is not.
    let env = Env::new();
    env.write_profile("default", "[instructions]\nmandatory = \"mandatory.md\"\n");
    std::fs::write(
        env.profiles_dir().join("default").join("mandatory.md"),
        "Always run the tests.\n",
    )
    .unwrap();

    env.run_with("demo", &antigravity(), &FakeBackend::default())
        .unwrap();

    let home_file = kit_dir(&env)
        .join("files")
        .join("home")
        .join(".gemini")
        .join("AGENTS.md");
    assert_eq!(
        std::fs::read_to_string(home_file).unwrap(),
        "Always run the tests.\n"
    );
}

#[test]
fn skills_store_warns_because_it_isnt_known_to_reach_antigravity() {
    // Decision 46 lists the agents the store serves; Antigravity isn't one.
    let env = Env::new();
    env.write_profile("default", "[skills]\nstore = \"readonly\"\n");

    assert_eq!(
        warnings(&env),
        "warning: skills.store is \"readonly\", but antigravity sandboxes don't support it: the \
         sbx skills store's skills don't reach sbxm-demo-antigravity; set skills.store = \"off\" \
         to silence this\n"
    );
}

#[test]
fn skills_store_off_doesnt_warn() {
    let env = Env::new();
    env.write_profile("default", "[skills]\nstore = \"off\"\n");

    assert_eq!(warnings(&env), "");
}

#[test]
fn claude_only_settings_warn_on_antigravity_too() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[skills]\nstore = \"off\"\n[harness.claude]\nmanaged_settings = \"managed.json\"\n",
    );
    std::fs::write(
        env.profiles_dir().join("default").join("managed.json"),
        "{}",
    )
    .unwrap();

    assert!(warnings(&env).contains("harness.claude.managed_settings is set, but antigravity"),);
}
