//! Slice 19: `new --harness gemini` creates a Gemini CLI sandbox with a
//! `harness-gemini` mixin (decisions 49, 68).

mod common;

use common::Env;
use sbxm::backend::{CreateSpec, FakeBackend, SkillsStore};
use sbxm::commands::new;
use sbxm::harness::Harness;

fn gemini() -> new::Options {
    new::Options {
        harness: Harness::Gemini,
        ..Default::default()
    }
}

fn gemini_kit_dir(env: &Env) -> std::path::PathBuf {
    env.kit_dir("demo").with_file_name("harness-gemini")
}

#[test]
fn creates_a_gemini_sandbox_with_a_harness_gemini_mixin() {
    let env = Env::new();
    let backend = FakeBackend::default();

    env.run_with("demo", &gemini(), &backend).unwrap();

    assert_eq!(
        backend.creates(),
        vec![CreateSpec {
            name: "sbxm-demo-gemini".into(),
            agent: "gemini".into(),
            workspace: env.base_dir().join("demo"),
            cpus: 4,
            memory: "8g".into(),
            skills: SkillsStore::ReadOnly,
            kits: vec![env.kit_dir("demo"), gemini_kit_dir(&env)],
        }]
    );
    insta::assert_snapshot!(
        std::fs::read_to_string(gemini_kit_dir(&env).join("spec.yaml")).unwrap(),
        @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-harness-gemini
    description: Generated by sbxm from profile 'default' for gemini. Do not edit.
    requires:
      agent: gemini
    "
    );
}

#[test]
fn mandatory_instructions_become_the_gemini_home_file() {
    let env = Env::new();
    env.write_profile("default", "[instructions]\nmandatory = \"mandatory.md\"\n");
    std::fs::write(
        env.profiles_dir().join("default").join("mandatory.md"),
        "Always run the tests.\n",
    )
    .unwrap();

    env.run_with("demo", &gemini(), &FakeBackend::default())
        .unwrap();

    let home_file = gemini_kit_dir(&env)
        .join("files")
        .join("home")
        .join(".gemini")
        .join("GEMINI.md");
    assert_eq!(
        std::fs::read_to_string(home_file).unwrap(),
        "Always run the tests.\n"
    );
}

#[test]
fn claude_only_settings_on_gemini_warn() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[harness.claude]\nmanaged_settings = \"managed.json\"\n",
    );
    std::fs::write(
        env.profiles_dir().join("default").join("managed.json"),
        "{}",
    )
    .unwrap();
    let mut warn = Vec::new();

    new::run(
        &env.config_dir(),
        "demo",
        &gemini(),
        &FakeBackend::default(),
        &mut warn,
    )
    .unwrap();

    assert_eq!(
        String::from_utf8(warn).unwrap(),
        "warning: harness.claude.managed_settings is set, but gemini sandboxes don't support \
         it: its settings (hooks included) don't reach sbxm-demo-gemini\n"
    );
}
