//! Slice 20: `new --harness pi` creates a Pi sandbox from the pinned Docker Hub
//! kit with a `harness-pi` mixin (decisions 73, 75).

mod common;

use common::Env;
use sbxm::backend::{CreateSpec, FakeBackend, SkillsStore};
use sbxm::commands::new;
use sbxm::harness::Harness;

fn pi() -> new::Options {
    new::Options {
        harness: Harness::Pi,
        ..Default::default()
    }
}

fn pi_kit_dir(env: &Env) -> std::path::PathBuf {
    env.kit_dir("demo").with_file_name("harness-pi")
}

/// Runs `new demo --harness pi` and returns its warnings.
fn pi_warnings(env: &Env) -> String {
    let mut warn = Vec::new();
    new::run(
        &env.config_dir(),
        "demo",
        &pi(),
        &FakeBackend::default(),
        &mut warn,
    )
    .unwrap();
    String::from_utf8(warn).unwrap()
}

#[test]
fn creates_a_pi_sandbox_from_the_pinned_kit() {
    let env = Env::new();
    let backend = FakeBackend::default();

    env.run_with("demo", &pi(), &backend).unwrap();

    assert_eq!(
        backend.creates(),
        vec![CreateSpec {
            name: "sbxm-demo-pi".into(),
            agent: "docker.io/sbx/pi-kit:20260924-d058fedc156325f87612d9bcd9bd313ab74ba100".into(),
            workspace: env.base_dir().join("demo"),
            cpus: 4,
            memory: "8g".into(),
            skills: SkillsStore::ReadOnly,
            kits: vec![env.kit_dir("demo"), pi_kit_dir(&env)],
        }]
    );
    insta::assert_snapshot!(
        std::fs::read_to_string(pi_kit_dir(&env).join("spec.yaml")).unwrap(),
        @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-harness-pi
    description: Generated by sbxm from profile 'default' for pi. Do not edit.
    requires:
      agent: pi
    "
    );
}

#[test]
fn mandatory_instructions_become_the_pi_home_file() {
    let env = Env::new();
    env.write_profile("default", "[instructions]\nmandatory = \"mandatory.md\"\n");
    std::fs::write(
        env.profiles_dir().join("default").join("mandatory.md"),
        "Always run the tests.\n",
    )
    .unwrap();

    env.run_with("demo", &pi(), &FakeBackend::default())
        .unwrap();

    let home_file = pi_kit_dir(&env)
        .join("files")
        .join("home")
        .join(".pi")
        .join("agent")
        .join("AGENTS.md");
    assert_eq!(
        std::fs::read_to_string(home_file).unwrap(),
        "Always run the tests.\n"
    );
}

#[test]
fn reference_instructions_on_pi_warn() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[instructions]\nreference = \"reference.md\"\n[skills]\nstore = \"off\"\n",
    );
    std::fs::write(
        env.profiles_dir().join("default").join("reference.md"),
        "Background.\n",
    )
    .unwrap();

    assert_eq!(
        pi_warnings(&env),
        "warning: instructions.reference is set, and pi sandboxes always load it (sbx writes it \
         as AGENTS.md above the workspace, and Pi reads parent folders): it takes up context in \
         every prompt in sbxm-demo-pi, not only on demand\n"
    );
}

#[test]
fn pi_without_reference_instructions_doesnt_warn() {
    let env = Env::new();
    env.write_profile("default", "[skills]\nstore = \"off\"\n");

    assert_eq!(pi_warnings(&env), "");
}

/// Decision 78: the `sbx` skills store doesn't serve Pi (decisions 46, 72).
#[test]
fn skills_store_on_pi_warns() {
    let env = Env::new();

    assert_eq!(
        pi_warnings(&env),
        "warning: skills.store is \"readonly\", but pi sandboxes don't support it: \
         the sbx skills store's skills don't reach sbxm-demo-pi; \
         set skills.store = \"off\" to silence this\n"
    );
}

#[test]
fn skills_store_off_on_pi_doesnt_warn() {
    let env = Env::new();
    env.write_profile("default", "[skills]\nstore = \"off\"\n");

    assert_eq!(pi_warnings(&env), "");
}
