//! Slice 18a: `new --harness codex` creates a Codex sandbox with a
//! `harness-codex` mixin, and state keeps one entry per harness (decision 68).
//! Slice 18b: Claude-only settings on a Codex sandbox warn loudly (decision 11).

mod common;

use assert_cmd::Command;
use common::Env;
use sbxm::backend::{CreateSpec, FakeBackend, SandboxInfo, SkillsStore};
use sbxm::commands::list::{self, ConfigStatus};
use sbxm::commands::new;
use sbxm::harness::Harness;

fn codex() -> new::Options {
    new::Options {
        harness: Harness::Codex,
        ..Default::default()
    }
}

fn codex_kit_dir(env: &Env) -> std::path::PathBuf {
    env.kit_dir("demo").with_file_name("harness-codex")
}

#[test]
fn creates_a_codex_sandbox_with_a_harness_codex_mixin() {
    let env = Env::new();
    let backend = FakeBackend::default();

    env.run_with("demo", &codex(), &backend).unwrap();

    assert_eq!(
        backend.creates(),
        vec![CreateSpec {
            name: "sbxm-demo-codex".into(),
            agent: "codex".into(),
            workspace: env.base_dir().join("demo"),
            cpus: 4,
            memory: "8g".into(),
            skills: SkillsStore::ReadOnly,
            kits: vec![env.kit_dir("demo"), codex_kit_dir(&env)],
        }]
    );
    insta::assert_snapshot!(
        std::fs::read_to_string(codex_kit_dir(&env).join("spec.yaml")).unwrap(),
        @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-harness-codex
    description: Generated by sbxm from profile 'default' for codex. Do not edit.
    requires:
      agent: codex
    "
    );
}

#[test]
fn mandatory_instructions_become_the_codex_home_file() {
    let env = Env::new();
    env.write_profile("default", "[instructions]\nmandatory = \"mandatory.md\"\n");
    std::fs::write(
        env.profiles_dir().join("default").join("mandatory.md"),
        "Always run the tests.\n",
    )
    .unwrap();

    env.run_with("demo", &codex(), &FakeBackend::default())
        .unwrap();

    let home_file = codex_kit_dir(&env)
        .join("files")
        .join("home")
        .join(".codex")
        .join("AGENTS.md");
    assert_eq!(
        std::fs::read_to_string(home_file).unwrap(),
        "Always run the tests.\n"
    );
}

#[test]
fn state_keeps_the_claude_entry_when_codex_is_added() {
    let env = Env::new();
    let backend = FakeBackend::default();

    env.run("demo", &backend).unwrap();
    env.run_with("demo", &codex(), &backend).unwrap();

    let path = env.base_dir().join(".sbxm").join("demo").join("state.json");
    let state: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    assert_eq!(state["sandboxes"]["claude"]["sandbox"], "sbxm-demo-claude");
    assert_eq!(state["sandboxes"]["codex"]["sandbox"], "sbxm-demo-codex");
}

#[test]
fn unsupported_harness_is_rejected_and_creates_nothing() {
    let env = Env::new();

    let output = Command::cargo_bin("sbxm")
        .unwrap()
        .env("SBXM_CONFIG_DIR", env.config_dir())
        .args(["new", "demo", "--harness", "opencode"])
        .output()
        .unwrap();

    assert!(!output.status.success());
    let stderr = String::from_utf8(output.stderr).unwrap();
    assert!(
        stderr.contains("invalid value 'opencode' for '--harness"),
        "{stderr}"
    );
    assert!(
        stderr.contains("[possible values: claude, codex, gemini, pi, antigravity]"),
        "{stderr}"
    );
    assert!(!env.base_dir().join("demo").exists());
    assert!(!env.base_dir().join(".sbxm").exists());
}

/// A profile setting both Claude-only settings, with their files.
fn write_claude_only_profile(env: &Env) {
    env.write_profile(
        "default",
        "[harness.claude]\nhome_files = \"home\"\nmanaged_settings = \"managed.json\"\n",
    );
    let dir = env.profiles_dir().join("default");
    std::fs::create_dir_all(dir.join("home").join(".claude")).unwrap();
    std::fs::write(dir.join("home").join(".claude").join("notes.md"), "notes\n").unwrap();
    std::fs::write(dir.join("managed.json"), "{}").unwrap();
}

/// Runs `new demo` and returns what it wrote to its warning output.
fn warnings(env: &Env, options: &new::Options, backend: &FakeBackend) -> String {
    let mut warn = Vec::new();
    new::run(&env.config_dir(), "demo", options, backend, &mut warn).unwrap();
    String::from_utf8(warn).unwrap()
}

#[test]
fn claude_only_settings_on_codex_warn_and_still_create() {
    let env = Env::new();
    write_claude_only_profile(&env);
    let backend = FakeBackend::default();

    let warnings = warnings(&env, &codex(), &backend);

    assert_eq!(
        warnings,
        "warning: harness.claude.home_files is set, but codex sandboxes don't support it: \
         none of its files reach sbxm-demo-codex\n\
         warning: harness.claude.managed_settings is set, but codex sandboxes don't support it: \
         its settings (hooks included) don't reach sbxm-demo-codex\n"
    );
    assert_eq!(backend.creates().len(), 1);
}

#[test]
fn claude_only_settings_on_claude_dont_warn() {
    let env = Env::new();
    write_claude_only_profile(&env);

    let warnings = warnings(&env, &new::Options::default(), &FakeBackend::default());

    assert_eq!(warnings, "");
}

/// Slice 18c: each harness has its own hash, over what reaches it (decision 69).
#[test]
fn claude_and_codex_hashes_differ() {
    let env = Env::new();
    let backend = FakeBackend::default();

    env.run("demo", &backend).unwrap();
    env.run_with("demo", &codex(), &backend).unwrap();

    let path = env.base_dir().join(".sbxm").join("demo").join("state.json");
    let state: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    assert_ne!(
        state["sandboxes"]["claude"]["config_hash"],
        state["sandboxes"]["codex"]["config_hash"]
    );
}

#[test]
fn claude_only_edit_shows_drift_on_the_claude_sandbox_only() {
    let env = Env::new();
    write_claude_only_profile(&env);
    let backend = FakeBackend::default();
    env.run("demo", &backend).unwrap();
    env.run_with("demo", &codex(), &backend).unwrap();

    std::fs::write(
        env.profiles_dir().join("default").join("managed.json"),
        r#"{"model": "changed"}"#,
    )
    .unwrap();

    let running = |name: &str, agent: &str| SandboxInfo {
        name: name.into(),
        agent: agent.into(),
        status: "running".into(),
    };
    let backend = FakeBackend::with_sandboxes(vec![
        running("sbxm-demo-claude", "claude"),
        running("sbxm-demo-codex", "codex"),
    ]);
    let configs: Vec<_> = list::entries(&env.config_dir(), &backend)
        .unwrap()
        .into_iter()
        .map(|e| (e.harness, e.config))
        .collect();
    assert_eq!(
        configs,
        vec![
            ("claude".to_owned(), Some(ConfigStatus::Changed)),
            ("codex".to_owned(), Some(ConfigStatus::Current)),
        ]
    );
}

#[test]
fn codex_without_claude_only_settings_doesnt_warn() {
    let env = Env::new();

    let warnings = warnings(&env, &codex(), &FakeBackend::default());

    assert_eq!(warnings, "");
}
