//! Slice 14: mandatory instructions reach `~/.claude/CLAUDE.md` through the
//! `harness-claude` mixin, reference instructions reach the common mixin's
//! `agentInstructions` (decisions 37, 62).

mod common;

use common::Env;
use sbxm::backend::FakeBackend;

fn harness_spec(env: &Env) -> String {
    std::fs::read_to_string(env.harness_kit_dir("demo").join("spec.yaml")).unwrap()
}

#[test]
fn every_sandbox_gets_a_harness_claude_mixin() {
    let env = Env::new();

    env.run("demo", &FakeBackend::default()).unwrap();

    insta::assert_snapshot!(harness_spec(&env), @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-harness-claude
    description: Generated by sbxm from profile 'default' for claude. Do not edit.
    requires:
      agent: claude
    ");
}

/// Writes `<profiles_dir>/default/<relative>`.
fn write_profile_file(env: &Env, relative: &str, contents: &str) {
    let path = env.profiles_dir().join("default").join(relative);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, contents).unwrap();
}

#[test]
fn mandatory_instructions_become_the_claude_home_file() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[instructions]\nmandatory = \"instructions/mandatory.md\"\n",
    );
    write_profile_file(&env, "instructions/mandatory.md", "Always run the tests.\n");

    env.run("demo", &FakeBackend::default()).unwrap();

    let home_file = env
        .harness_kit_dir("demo")
        .join("files")
        .join("home")
        .join(".claude")
        .join("CLAUDE.md");
    assert_eq!(
        std::fs::read_to_string(home_file).unwrap(),
        "Always run the tests.\n"
    );
}

#[test]
fn reference_instructions_become_agent_instructions() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[instructions]\nreference = \"instructions/reference.md\"\n",
    );
    write_profile_file(&env, "instructions/reference.md", "Style guide.\n");

    env.run("demo", &FakeBackend::default()).unwrap();

    let text = std::fs::read_to_string(env.kit_dir("demo").join("spec.yaml")).unwrap();
    let spec: serde_json::Value = serde_norway::from_str(&text).unwrap();
    assert_eq!(spec["agentInstructions"]["content"], "Style guide.\n");
}
