//! Slice 14: mandatory instructions reach `~/.claude/CLAUDE.md` through the
//! `harness-claude` mixin, reference instructions reach the common mixin's
//! `agentInstructions` (decisions 37, 62).

mod common;

use common::Env;
use sbxm::backend::FakeBackend;

fn harness_spec(env: &Env) -> String {
    std::fs::read_to_string(env.harness_kit_dir("demo").join("spec.yaml")).unwrap()
}

#[test]
fn every_sandbox_gets_a_harness_claude_mixin() {
    let env = Env::new();

    env.run("demo", &FakeBackend::default()).unwrap();

    insta::assert_snapshot!(harness_spec(&env), @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-harness-claude
    description: Generated by sbxm from profile 'default' for claude. Do not edit.
    requires:
      agent: claude
    ");
}

/// Writes `<profiles_dir>/default/<relative>`.
fn write_profile_file(env: &Env, relative: &str, contents: &str) {
    let path = env.profiles_dir().join("default").join(relative);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, contents).unwrap();
}

#[test]
fn mandatory_instructions_become_the_claude_home_file() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[instructions]\nmandatory = \"instructions/mandatory.md\"\n",
    );
    write_profile_file(&env, "instructions/mandatory.md", "Always run the tests.\n");

    env.run("demo", &FakeBackend::default()).unwrap();

    let home_file = env
        .harness_kit_dir("demo")
        .join("files")
        .join("home")
        .join(".claude")
        .join("CLAUDE.md");
    assert_eq!(
        std::fs::read_to_string(home_file).unwrap(),
        "Always run the tests.\n"
    );
}

#[test]
fn reference_instructions_become_agent_instructions() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[instructions]\nreference = \"instructions/reference.md\"\n",
    );
    write_profile_file(&env, "instructions/reference.md", "Style guide.\n");

    env.run("demo", &FakeBackend::default()).unwrap();

    let text = std::fs::read_to_string(env.kit_dir("demo").join("spec.yaml")).unwrap();
    let spec: serde_json::Value = serde_norway::from_str(&text).unwrap();
    assert_eq!(spec["agentInstructions"]["content"], "Style guide.\n");
}

/// Runs `new demo` with `mandatory = <path>`, expecting an error; checks
/// nothing was created.
fn rejected_mandatory(env: &Env, path: &str) -> String {
    let path = toml::Value::String(path.to_owned());
    env.write_profile("default", &format!("[instructions]\nmandatory = {path}\n"));
    let backend = FakeBackend::default();
    let err = env.run("demo", &backend).unwrap_err();
    assert!(backend.log().is_empty(), "{:?}", backend.log());
    assert!(!env.base_dir().join("demo").exists());
    assert!(!env.base_dir().join(".sbxm").exists());
    format!("{err:#}")
}

fn profile_toml(env: &Env) -> String {
    env.profiles_dir()
        .join("default")
        .join("profile.toml")
        .display()
        .to_string()
}

#[test]
fn missing_instructions_file_is_an_error() {
    let env = Env::new();

    let message = rejected_mandatory(&env, "instructions/missing.md");

    let missing = env
        .profiles_dir()
        .join("default")
        .join("instructions/missing.md");
    assert!(
        message.contains(&format!(
            "instructions.mandatory file {} (profile 'default') is missing or not a file; \
             create it or fix {}",
            missing.display(),
            profile_toml(&env)
        )),
        "{message}"
    );
}

#[test]
fn instructions_path_outside_the_profile_is_rejected() {
    let env = Env::new();
    let outside = env.tmp.path().join("outside.md");
    std::fs::write(&outside, "x").unwrap();

    for path in ["../outside.md", outside.to_str().unwrap()] {
        let message = rejected_mandatory(&env, path);

        assert!(
            message.contains(&format!(
                "instructions.mandatory = \"{path}\" in profile 'default' must be a relative \
                 path inside {}; fix it in {}",
                env.profiles_dir().join("default").display(),
                profile_toml(&env)
            )),
            "{path}: {message}"
        );
    }
}

/// Runs `new <project>` and returns the config hash from its state.
fn created_hash(env: &Env, project: &str) -> String {
    env.run(project, &FakeBackend::default()).unwrap();
    let path = env
        .base_dir()
        .join(".sbxm")
        .join(project)
        .join("state.json");
    let state: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(path).unwrap()).unwrap();
    state["sandboxes"]["claude"]["config_hash"]
        .as_str()
        .unwrap()
        .to_owned()
}

#[test]
fn editing_an_instructions_file_changes_the_hash() {
    let env = Env::new();
    env.write_profile("default", "[instructions]\nmandatory = \"rules.md\"\n");
    write_profile_file(&env, "rules.md", "Rule one.\n");
    let before = created_hash(&env, "one");

    write_profile_file(&env, "rules.md", "Rule one.\nRule two.\n");

    assert_ne!(before, created_hash(&env, "two"));
}

#[test]
fn moving_an_instructions_file_keeps_the_hash() {
    let env = Env::new();
    env.write_profile("default", "[instructions]\nmandatory = \"rules.md\"\n");
    write_profile_file(&env, "rules.md", "Rule one.\n");
    let before = created_hash(&env, "one");

    env.write_profile("default", "[instructions]\nmandatory = \"docs/rules.md\"\n");
    write_profile_file(&env, "docs/rules.md", "Rule one.\n");

    assert_eq!(before, created_hash(&env, "two"));
}

#[test]
fn project_instructions_override_the_profile_and_resolve_in_its_folder() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[instructions]\nmandatory = \"rules.md\"\nreference = \"ref.md\"\n",
    );
    write_profile_file(&env, "rules.md", "Profile rules.\n");
    write_profile_file(&env, "ref.md", "Profile reference.\n");
    let metadata = env.base_dir().join(".sbxm").join("demo");
    std::fs::create_dir_all(&metadata).unwrap();
    std::fs::write(
        metadata.join("sandbox.toml"),
        "[instructions]\nmandatory = \"project-rules.md\"\n",
    )
    .unwrap();
    std::fs::write(metadata.join("project-rules.md"), "Project rules.\n").unwrap();

    env.run("demo", &FakeBackend::default()).unwrap();

    let claude_md = env
        .harness_kit_dir("demo")
        .join("files/home/.claude/CLAUDE.md");
    assert_eq!(
        std::fs::read_to_string(claude_md).unwrap(),
        "Project rules.\n"
    );
    let text = std::fs::read_to_string(env.kit_dir("demo").join("spec.yaml")).unwrap();
    let spec: serde_json::Value = serde_norway::from_str(&text).unwrap();
    assert_eq!(spec["agentInstructions"]["content"], "Profile reference.\n");
}
