//! Slice 14: mandatory instructions reach `~/.claude/CLAUDE.md` through the
//! `harness-claude` mixin, reference instructions reach the common mixin's
//! `agentInstructions` (decisions 37, 62).

mod common;

use common::Env;
use sbxm::backend::FakeBackend;

fn harness_spec(env: &Env) -> String {
    std::fs::read_to_string(env.harness_kit_dir("demo").join("spec.yaml")).unwrap()
}

#[test]
fn every_sandbox_gets_a_harness_claude_mixin() {
    let env = Env::new();

    env.run("demo", &FakeBackend::default()).unwrap();

    insta::assert_snapshot!(harness_spec(&env), @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-harness-claude
    description: Generated by sbxm from profile 'default' for claude. Do not edit.
    requires:
      agent: claude
    ");
}
