//! Slice 10b: the profile's network rules reach the sandbox through a
//! generated `common` mixin kit.

mod common;

use std::path::PathBuf;

use common::Env;
use sbxm::backend::FakeBackend;

fn kit_dir(env: &Env) -> PathBuf {
    env.kit_dir("demo")
}

fn spec(env: &Env) -> String {
    std::fs::read_to_string(kit_dir(env).join("spec.yaml")).unwrap()
}

#[test]
fn profile_network_becomes_the_common_mixin() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[network]\n\
         allow = [\"github.com\", \"*.githubusercontent.com\"]\n\
         deny = [\"telemetry.example.com\"]\n",
    );

    env.run("demo", &FakeBackend::default()).unwrap();

    insta::assert_snapshot!(spec(&env), @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-common
    description: Generated by sbxm from profile 'default'. Do not edit.
    permissions:
      network:
        allow:
        - github.com
        - '*.githubusercontent.com'
        deny:
        - telemetry.example.com
    ");
}

#[test]
fn profile_without_network_gets_empty_lists() {
    let env = Env::new();

    env.run("demo", &FakeBackend::default()).unwrap();

    insta::assert_snapshot!(spec(&env), @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-common
    description: Generated by sbxm from profile 'default'. Do not edit.
    permissions:
      network:
        allow: []
        deny: []
    ");
}

#[test]
fn kit_is_validated_before_the_sandbox_is_created() {
    let env = Env::new();
    let backend = FakeBackend::default();

    env.run("demo", &backend).unwrap();

    assert_eq!(
        backend.log(),
        [
            format!("validate {}", kit_dir(&env).display()),
            "create sbxm-demo-claude".to_owned()
        ]
    );
}

#[test]
fn invalid_kit_aborts_before_anything_is_created() {
    let env = Env::new();
    let backend = FakeBackend::with_invalid_kit("manifest: bad network pattern");

    let err = env.run("demo", &backend).unwrap_err();

    let message = format!("{err:#}");
    assert!(
        message.contains(&format!(
            "generated kit {} is invalid: manifest: bad network pattern;",
            kit_dir(&env).display()
        )),
        "{message}"
    );
    assert!(message.contains("profile 'default'"), "{message}");
    assert!(backend.creates().is_empty());
    assert!(!env.base_dir().join("demo").exists());
}

#[test]
fn profile_env_becomes_environment_variables() {
    let env = Env::new();
    env.write_profile("default", "[env]\nZED = \"last\"\nEXAMPLE_FLAG = \"1\"\n");

    env.run("demo", &FakeBackend::default()).unwrap();

    insta::assert_snapshot!(spec(&env), @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-common
    description: Generated by sbxm from profile 'default'. Do not edit.
    permissions:
      network:
        allow: []
        deny: []
    environment:
      variables:
        EXAMPLE_FLAG: '1'
        ZED: last
    ");
}
