//! Slice 10b: the profile's network rules reach the sandbox through a
//! generated `common` mixin kit.

mod common;

use std::path::PathBuf;

use common::Env;
use sbxm::backend::FakeBackend;

fn kit_dir(env: &Env) -> PathBuf {
    env.base_dir()
        .join(".sbxm")
        .join("demo")
        .join("kits")
        .join("common")
}

fn spec(env: &Env) -> String {
    std::fs::read_to_string(kit_dir(env).join("spec.yaml")).unwrap()
}

#[test]
fn profile_network_becomes_the_common_mixin() {
    let env = Env::new();
    env.write_profile(
        "default",
        "[network]\n\
         allow = [\"github.com\", \"*.githubusercontent.com\"]\n\
         deny = [\"telemetry.example.com\"]\n",
    );

    env.run("demo", &FakeBackend::default()).unwrap();

    insta::assert_snapshot!(spec(&env), @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-common
    description: Generated by sbxm from profile 'default'. Do not edit.
    permissions:
      network:
        allow:
        - github.com
        - '*.githubusercontent.com'
        deny:
        - telemetry.example.com
    ");
}

#[test]
fn profile_without_network_gets_empty_lists() {
    let env = Env::new();

    env.run("demo", &FakeBackend::default()).unwrap();

    insta::assert_snapshot!(spec(&env), @r"
    schemaVersion: '2'
    kind: mixin
    name: sbxm-common
    description: Generated by sbxm from profile 'default'. Do not edit.
    permissions:
      network:
        allow: []
        deny: []
    ");
}
