use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use super::harness_label;
use crate::backend::SandboxBackend;
use crate::config::GlobalConfig;
use crate::confirm::Confirm;
use crate::harness::Harness;
use crate::{project, state};

#[derive(Debug, Default)]
pub struct Options {
    /// Also delete the workspace and `.sbxm/<project>/`.
    pub purge: bool,
    /// Skip the confirmation (required for `purge` without a terminal).
    pub yes: bool,
    /// Which of the project's sandboxes plain `rm` removes.
    pub harness: Harness,
}

/// Removes the project's sandbox and its state. The workspace is kept unless
/// `purge` is set and the user confirms (decision 32).
pub fn run(
    config_dir: &Path,
    name: &str,
    options: &Options,
    backend: &dyn SandboxBackend,
    confirm: &dyn Confirm,
) -> Result<()> {
    project::validate_name(name)?;
    let config = GlobalConfig::load(config_dir)?;
    let metadata_dir = project::metadata_dir(&config.base_dir, name);
    let state = state::load(&metadata_dir)?;
    let harness = options.harness.as_str();
    let entry = state.as_ref().and_then(|s| s.sandboxes.get(harness));
    let sandbox = entry.map(|s| s.sandbox.clone());

    if !options.purge {
        let Some(sandbox) = sandbox else {
            bail!(
                "no sbxm {}sandbox for project '{name}'; `sbxm list` shows existing ones",
                harness_label(options.harness)
            );
        };
        let hash = entry.and_then(|s| s.config_hash.clone());
        let last = state.as_ref().is_some_and(|s| s.sandboxes.len() == 1);
        let kits = metadata_dir.join("kits");
        if last && kits.symlink_metadata().is_ok() {
            check_deletable(&kits)?;
        }
        remove_sandbox(backend, &sandbox)?;
        if last && kits.symlink_metadata().is_ok() {
            // Generated by sbxm; the project's own files (e.g. sandbox.toml) stay.
            fs::remove_dir_all(&kits)
                .with_context(|| format!("cannot delete {}", kits.display()))?;
        }
        state::remove_sandbox(&metadata_dir, harness)?;
        if let Some(hash) = &hash {
            delete_unused_kit(&metadata_dir, hash)?;
        }
        return Ok(());
    }

    let dirs: Vec<PathBuf> = [config.base_dir.join(name), metadata_dir]
        .into_iter()
        .filter(|dir| dir.symlink_metadata().is_ok())
        .collect();
    if dirs.is_empty() && sandbox.is_none() {
        bail!("nothing to purge for project '{name}'; `sbxm list` shows existing ones");
    }
    for dir in &dirs {
        check_deletable(dir)?;
    }
    let listing: Vec<String> = dirs.iter().map(|d| format!("  {}", d.display())).collect();
    let listing = listing.join("\n");
    if !options.yes {
        if !confirm.is_interactive() {
            bail!("refusing to purge without a terminal; pass --yes to delete:\n{listing}");
        }
        if !confirm.confirm(&format!(
            "Permanently delete these directories?\n{listing}\n"
        ))? {
            bail!("purge cancelled; nothing was deleted");
        }
    }

    if let Some(sandbox) = &sandbox {
        remove_sandbox(backend, sandbox)?;
    }
    for dir in &dirs {
        fs::remove_dir_all(dir).with_context(|| format!("cannot delete {}", dir.display()))?;
    }
    Ok(())
}

/// `sbx rm` fails for a sandbox that's already gone, which is the outcome
/// `rm` wants, so a failure only counts if `sbx ls` still lists the sandbox.
fn remove_sandbox(backend: &dyn SandboxBackend, sandbox: &str) -> Result<()> {
    let Err(err) = backend.remove(sandbox) else {
        return Ok(());
    };
    match backend.list() {
        Ok(sandboxes) if !sandboxes.iter().any(|s| s.name == sandbox) => Ok(()),
        _ => Err(err),
    }
}

/// Deletes `kits/<prefix>` of `hash` unless a sandbox in the project's state
/// still uses it (decisions 55, 70).
pub(crate) fn delete_unused_kit(metadata_dir: &Path, hash: &str) -> Result<()> {
    // Read from state.json, so check it before building a path from it.
    let Some(prefix) = hash.get(..12) else {
        return Ok(());
    };
    if !prefix.chars().all(|c| c.is_ascii_hexdigit()) {
        return Ok(());
    }
    let in_use = state::load(metadata_dir)?.is_some_and(|s| {
        s.sandboxes
            .values()
            .any(|e| e.config_hash.as_deref().and_then(|h| h.get(..12)) == Some(prefix))
    });
    let dir = metadata_dir.join("kits").join(prefix);
    if in_use || dir.symlink_metadata().is_err() {
        return Ok(());
    }
    check_deletable(&dir)?;
    fs::remove_dir_all(&dir).with_context(|| format!("cannot delete {}", dir.display()))
}

/// Refuses links (deleting through one could reach outside the base dir) and
/// anything whose real location isn't directly under its expected parent.
pub(crate) fn check_deletable(dir: &Path) -> Result<()> {
    if dir.symlink_metadata()?.file_type().is_symlink() {
        bail!(
            "{} is a symlink or junction; remove the link yourself if you want it gone",
            dir.display()
        );
    }
    let parent = dir.parent().context("path has no parent")?;
    let real = fs::canonicalize(dir)?;
    if real.parent() != Some(fs::canonicalize(parent)?.as_path()) {
        bail!(
            "{} resolves to {}, outside {}; not deleting it",
            dir.display(),
            real.display(),
            parent.display()
        );
    }
    Ok(())
}
