use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use super::HARNESS;
use crate::backend::SandboxBackend;
use crate::config::GlobalConfig;
use crate::confirm::Confirm;
use crate::{project, state};

#[derive(Debug, Default)]
pub struct Options {
    /// Also delete the workspace and `.sbxm/<project>/`.
    pub purge: bool,
    /// Skip the confirmation (required for `purge` without a terminal).
    pub yes: bool,
}

/// Removes the project's sandbox and its state. The workspace is kept unless
/// `purge` is set and the user confirms (decision 32).
pub fn run(
    config_dir: &Path,
    name: &str,
    options: &Options,
    backend: &dyn SandboxBackend,
    confirm: &dyn Confirm,
) -> Result<()> {
    project::validate_name(name)?;
    let config = GlobalConfig::load(config_dir)?;
    let metadata_dir = project::metadata_dir(&config.base_dir, name);
    let state = state::load(&metadata_dir)?;
    let sandbox = state
        .as_ref()
        .and_then(|s| s.sandboxes.get(HARNESS))
        .map(|s| s.sandbox.clone());

    if !options.purge {
        let Some(sandbox) = sandbox else {
            bail!("no sbxm sandbox for project '{name}'; `sbxm list` shows existing ones");
        };
        let last = state.as_ref().is_some_and(|s| s.sandboxes.len() == 1);
        let kits = metadata_dir.join("kits");
        if last && kits.symlink_metadata().is_ok() {
            check_deletable(&kits)?;
        }
        backend.remove(&sandbox)?;
        if last && kits.symlink_metadata().is_ok() {
            // Generated by sbxm; the project's own files (e.g. sandbox.toml) stay.
            fs::remove_dir_all(&kits)
                .with_context(|| format!("cannot delete {}", kits.display()))?;
        }
        return state::remove_sandbox(&metadata_dir, HARNESS);
    }

    let dirs: Vec<PathBuf> = [config.base_dir.join(name), metadata_dir]
        .into_iter()
        .filter(|dir| dir.symlink_metadata().is_ok())
        .collect();
    if dirs.is_empty() && sandbox.is_none() {
        bail!("nothing to purge for project '{name}'; `sbxm list` shows existing ones");
    }
    for dir in &dirs {
        check_deletable(dir)?;
    }
    let listing: Vec<String> = dirs.iter().map(|d| format!("  {}", d.display())).collect();
    let listing = listing.join("\n");
    if !options.yes {
        if !confirm.is_interactive() {
            bail!("refusing to purge without a terminal; pass --yes to delete:\n{listing}");
        }
        if !confirm.confirm(&format!(
            "Permanently delete these directories?\n{listing}\n"
        ))? {
            bail!("purge cancelled; nothing was deleted");
        }
    }

    if let Some(sandbox) = &sandbox {
        backend.remove(sandbox)?;
    }
    for dir in &dirs {
        fs::remove_dir_all(dir).with_context(|| format!("cannot delete {}", dir.display()))?;
    }
    Ok(())
}

/// Refuses links (deleting through one could reach outside the base dir) and
/// anything whose real location isn't directly under its expected parent.
pub(crate) fn check_deletable(dir: &Path) -> Result<()> {
    if dir.symlink_metadata()?.file_type().is_symlink() {
        bail!(
            "{} is a symlink or junction; remove the link yourself if you want it gone",
            dir.display()
        );
    }
    let parent = dir.parent().context("path has no parent")?;
    let real = fs::canonicalize(dir)?;
    if real.parent() != Some(fs::canonicalize(parent)?.as_path()) {
        bail!(
            "{} resolves to {}, outside {}; not deleting it",
            dir.display(),
            real.display(),
            parent.display()
        );
    }
    Ok(())
}
