//! Generated `sbx` kits (schemaVersion "2" mixins). The only module that knows
//! the kit format (decisions 36, 39). Spec:
//! <https://github.com/docker/sbx-kits-contrib/blob/main/spec/SPEC-v2.md>.

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::Serialize;

use crate::config::{InstallStep, Profile};
use crate::harness::Harness;

/// The fields sbxm emits; field order is the order in `spec.yaml`.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Spec {
    schema_version: &'static str,
    kind: &'static str,
    name: &'static str,
    description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    requires: Option<Requires>,
    #[serde(skip_serializing_if = "Option::is_none")]
    permissions: Option<Permissions>,
    #[serde(skip_serializing_if = "Option::is_none")]
    environment: Option<Environment>,
    #[serde(skip_serializing_if = "Option::is_none")]
    setup: Option<Setup>,
    /// Reference material only: `sbx` surfaces it on demand (decision 37).
    #[serde(skip_serializing_if = "Option::is_none")]
    agent_instructions: Option<AgentInstructions>,
    /// Written to `files/home/<path>`, not to `spec.yaml`.
    #[serde(skip)]
    home_files: Vec<(PathBuf, Vec<u8>)>,
}

#[derive(Debug, Serialize)]
struct AgentInstructions {
    content: String,
}

/// Pins a mixin to one harness; composing it with another is an error.
#[derive(Debug, Serialize)]
struct Requires {
    agent: &'static str,
}

#[derive(Debug, Serialize)]
struct Setup {
    install: Vec<Install>,
}

/// Run via `sh -c` once at create, after the agent kit's own steps, in
/// `--kit` order.
#[derive(Debug, Serialize)]
struct Install {
    command: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    user: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    description: Option<String>,
}

impl From<&InstallStep> for Install {
    fn from(step: &InstallStep) -> Self {
        Install {
            command: step.command.clone(),
            user: step.user.clone(),
            description: step.description.clone(),
        }
    }
}

#[derive(Debug, Serialize)]
struct Environment {
    /// Sorted, so the same profile always gives byte-identical output.
    variables: BTreeMap<String, String>,
}

#[derive(Debug, Serialize)]
struct Permissions {
    network: Network,
}

#[derive(Debug, Serialize)]
struct Network {
    allow: Vec<String>,
    deny: Vec<String>,
}

/// The `common` mixin: everything in the profile that applies to any harness,
/// plus `SBXM_CONFIG_HASH`/`SBXM_PROFILE` so every sandbox records where it
/// came from (decision 55; the profile can't set `SBXM_` names).
pub fn common(profile_name: &str, profile: &Profile, config_hash: &str) -> Spec {
    let mut variables = profile.env.clone();
    variables.insert("SBXM_CONFIG_HASH".into(), config_hash.into());
    variables.insert("SBXM_PROFILE".into(), profile_name.into());
    Spec {
        schema_version: "2",
        kind: "mixin",
        name: "sbxm-common",
        description: format!("Generated by sbxm from profile '{profile_name}'. Do not edit."),
        requires: None,
        permissions: Some(Permissions {
            network: Network {
                allow: profile.network.allow.clone(),
                deny: profile.network.deny.clone(),
            },
        }),
        environment: Some(Environment { variables }),
        setup: (!profile.setup.install.is_empty()).then(|| Setup {
            install: profile.setup.install.iter().map(Install::from).collect(),
        }),
        agent_instructions: profile
            .reference_instructions
            .clone()
            .map(|content| AgentInstructions { content }),
        home_files: Vec::new(),
    }
}

/// The `harness-<h>` mixin: what only applies to one harness. Mandatory
/// instructions go in its always-loaded user-level file (decisions 37, 62).
/// For Claude, the profile's `harness.claude.home_files` (decision 63) and
/// managed settings (decision 64) join them.
pub fn harness(profile_name: &str, profile: &Profile, harness: Harness) -> Spec {
    let profile = harness.applied(profile);
    let mandatory = profile
        .mandatory_instructions
        .iter()
        .map(|text| (harness.instructions_file(), text.clone().into_bytes()));
    let copied = profile
        .claude_home_files
        .iter()
        .map(|(relative, bytes)| (relative.split('/').collect(), bytes.clone()));
    let home_files = mandatory.chain(copied).collect();
    let (name, agent) = match harness {
        Harness::Claude => ("sbxm-harness-claude", "claude"),
        Harness::Codex => ("sbxm-harness-codex", "codex"),
    };
    Spec {
        schema_version: "2",
        kind: "mixin",
        name,
        description: format!(
            "Generated by sbxm from profile '{profile_name}' for {agent}. Do not edit."
        ),
        requires: Some(Requires { agent }),
        permissions: None,
        environment: None,
        setup: profile
            .claude_managed_settings
            .as_deref()
            .map(|json| Setup {
                install: vec![write_managed_settings(json)],
            }),
        agent_instructions: None,
        home_files,
    }
}

/// A root step writing Claude's managed settings, which take precedence over
/// the settings the agent can edit without `sudo` (decisions 59, 64). `files/`
/// can't target `/etc`. `json` is one line, so it can't end the quoted
/// heredoc early, and escaping `$` keeps `${{` (a kit expression) out.
fn write_managed_settings(json: &str) -> Install {
    let json = json.replace('$', "\\u0024");
    let file = "/etc/claude-code/managed-settings.json";
    Install {
        command: format!(
            "set -e\n\
             mkdir -p /etc/claude-code\n\
             cat > {file} <<'SBXM_EOF'\n\
             {json}\n\
             SBXM_EOF\n\
             chmod 644 {file}\n"
        ),
        user: Some("0".into()),
        description: Some("sbxm: write Claude managed settings".into()),
    }
}

/// Every mixin for a sandbox, named by its kit subdirectory, in the order
/// they're passed to `sbx create` (decision 62).
pub fn all(
    profile_name: &str,
    profile: &Profile,
    config_hash: &str,
    harness: Harness,
) -> [(&'static str, Spec); 2] {
    let harness_dir = match harness {
        Harness::Claude => "harness-claude",
        Harness::Codex => "harness-codex",
    };
    [
        ("common", common(profile_name, profile, config_hash)),
        (harness_dir, self::harness(profile_name, profile, harness)),
    ]
}

impl Spec {
    /// The contents of `spec.yaml`.
    pub fn yaml(&self) -> Result<String> {
        Ok(serde_norway::to_string(self)?)
    }

    /// Paths under `files/home/`, `/`-separated.
    pub fn home_paths(&self) -> impl Iterator<Item = String> + '_ {
        self.home_files.iter().map(|(relative, _)| {
            let parts: Vec<_> = relative.iter().map(|p| p.to_string_lossy()).collect();
            parts.join("/")
        })
    }
}

/// Writes `<dir>/spec.yaml` and `<dir>/files/home/…`, creating `dir`.
pub fn write(dir: &Path, spec: &Spec) -> Result<()> {
    fs::create_dir_all(dir).with_context(|| format!("cannot create {}", dir.display()))?;
    let path = dir.join("spec.yaml");
    fs::write(&path, spec.yaml()?).with_context(|| format!("cannot write {}", path.display()))?;
    for (relative, bytes) in &spec.home_files {
        let path = dir.join("files").join("home").join(relative);
        let parent = path.parent().expect("home file has a parent");
        fs::create_dir_all(parent)
            .with_context(|| format!("cannot create {}", parent.display()))?;
        fs::write(&path, bytes).with_context(|| format!("cannot write {}", path.display()))?;
    }
    Ok(())
}
