//! Generated `sbx` kits (schemaVersion "2" mixins). The only module that knows
//! the kit format (decisions 36, 39). Spec:
//! <https://github.com/docker/sbx-kits-contrib/blob/main/spec/SPEC-v2.md>.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;

use crate::config::Profile;

/// The fields sbxm emits; field order is the order in `spec.yaml`.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Spec {
    schema_version: &'static str,
    kind: &'static str,
    name: &'static str,
    description: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    requires: Option<Requires>,
    #[serde(skip_serializing_if = "Option::is_none")]
    permissions: Option<Permissions>,
    #[serde(skip_serializing_if = "Option::is_none")]
    environment: Option<Environment>,
}

/// Pins a mixin to one harness; composing it with another is an error.
#[derive(Debug, Serialize)]
struct Requires {
    agent: &'static str,
}

#[derive(Debug, Serialize)]
struct Environment {
    /// Sorted, so the same profile always gives byte-identical output.
    variables: BTreeMap<String, String>,
}

#[derive(Debug, Serialize)]
struct Permissions {
    network: Network,
}

#[derive(Debug, Serialize)]
struct Network {
    allow: Vec<String>,
    deny: Vec<String>,
}

/// The `common` mixin: everything in the profile that applies to any harness,
/// plus `SBXM_CONFIG_HASH`/`SBXM_PROFILE` so every sandbox records where it
/// came from (decision 55; the profile can't set `SBXM_` names).
pub fn common(profile_name: &str, profile: &Profile, config_hash: &str) -> Spec {
    let mut variables = profile.env.clone();
    variables.insert("SBXM_CONFIG_HASH".into(), config_hash.into());
    variables.insert("SBXM_PROFILE".into(), profile_name.into());
    Spec {
        schema_version: "2",
        kind: "mixin",
        name: "sbxm-common",
        description: format!("Generated by sbxm from profile '{profile_name}'. Do not edit."),
        requires: None,
        permissions: Some(Permissions {
            network: Network {
                allow: profile.network.allow.clone(),
                deny: profile.network.deny.clone(),
            },
        }),
        environment: Some(Environment { variables }),
    }
}

/// The `harness-claude` mixin: what only applies to Claude Code
/// (decision 62).
pub fn harness_claude(profile_name: &str) -> Spec {
    Spec {
        schema_version: "2",
        kind: "mixin",
        name: "sbxm-harness-claude",
        description: format!(
            "Generated by sbxm from profile '{profile_name}' for claude. Do not edit."
        ),
        requires: Some(Requires { agent: "claude" }),
        permissions: None,
        environment: None,
    }
}

/// Writes `<dir>/spec.yaml`, creating `dir`.
pub fn write(dir: &Path, spec: &Spec) -> Result<()> {
    fs::create_dir_all(dir).with_context(|| format!("cannot create {}", dir.display()))?;
    let path = dir.join("spec.yaml");
    fs::write(&path, serde_norway::to_string(spec)?)
        .with_context(|| format!("cannot write {}", path.display()))
}
