//! Generated `sbx` kits (schemaVersion "2" mixins). The only module that knows
//! the kit format (decisions 36, 39). Spec:
//! <https://github.com/docker/sbx-kits-contrib/blob/main/spec/SPEC-v2.md>.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;

use crate::config::Profile;

/// The fields sbxm emits; field order is the order in `spec.yaml`.
#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Spec {
    schema_version: &'static str,
    kind: &'static str,
    name: &'static str,
    description: String,
    permissions: Permissions,
    #[serde(skip_serializing_if = "Option::is_none")]
    environment: Option<Environment>,
}

#[derive(Debug, Serialize)]
struct Environment {
    /// Sorted, so the same profile always gives byte-identical output.
    variables: BTreeMap<String, String>,
}

#[derive(Debug, Serialize)]
struct Permissions {
    network: Network,
}

#[derive(Debug, Serialize)]
struct Network {
    allow: Vec<String>,
    deny: Vec<String>,
}

/// The `common` mixin: everything in the profile that applies to any harness.
pub fn common(profile_name: &str, profile: &Profile) -> Spec {
    Spec {
        schema_version: "2",
        kind: "mixin",
        name: "sbxm-common",
        description: format!("Generated by sbxm from profile '{profile_name}'. Do not edit."),
        permissions: Permissions {
            network: Network {
                allow: profile.network.allow.clone(),
                deny: profile.network.deny.clone(),
            },
        },
        environment: (!profile.env.is_empty()).then(|| Environment {
            variables: profile.env.clone(),
        }),
    }
}

/// Writes `<dir>/spec.yaml`, creating `dir`.
pub fn write(dir: &Path, spec: &Spec) -> Result<()> {
    fs::create_dir_all(dir).with_context(|| format!("cannot create {}", dir.display()))?;
    let path = dir.join("spec.yaml");
    fs::write(&path, serde_norway::to_string(spec)?)
        .with_context(|| format!("cannot write {}", path.display()))
}
